languages = [
    "Afrikaans", "Albanian", "Amharic", "Arabic", "Armenian", "Assamese",
    "Azerbaijani", "Basque", "Belarusian", "Bosnian",
    "Bulgarian", "Burmese", "Catalan", "Central Kurdish", "Chinese (Simplified)",
    "Chinese (Traditional)", "Corsican", "Croatian", "Czech", "Danish", "Dutch",
    "English", "Estonian",  "Filipino", "Finnish", "French", "Galician", 
    "Georgian", "German", "Goan Konkani", "Greek", "Guarani", "Gujarati", "Haitian Creole",
    "Hawaiian", "Hebrew", "Hindi", "Hmong", "Hungarian", "Icelandic", "Indonesian", "Irish",
    "Italian", "Japanese", "Javanese", "Kannada", "Kazakh", "Khmer", "Kinyarwanda", "Korean", 
    "Kurdish", "Kyrgyz", "Lao", "Latin", "Latvian", "Lingala", "Lithuanian", "Luxembourgish",
    "Macedonian",  "Malagasy", "Malay", "Malayalam", "Maltese", 
    "Māori", "Marathi",  "Mongolian", "Nepali", "Northern Sotho", "Norwegian", "Nyanja", "Odia",
    "Oromo", "Pashto", "Persian", "Polish", "Portuguese", "Punjabi", "Quechua", "Romanian", "Russian",
    "Samoan", "Sanskrit", "Scottish Gaelic", "Serbian", "Shona", "Sindhi", "Sinhala", "Slovak", "Slovenian",
    "Somali", "Southern Sotho", "Spanish", "Sundanese", "Swahili", "Swedish", "Tajik", "Tamil", "Tatar",
    "Telugu", "Thai", "Tigrinya", "Tsonga", "Turkish", "Turkmen", "Ukrainian", "Urdu", "Uyghur", "Uzbek",
    "Vietnamese", "Welsh", "Western Frisian", "Xhosa", "Yiddish", "Yoruba", "Zulu"
]
language_dict = {
    "af": "Afrikaans", "sq": "Albanian", "am": "Amharic", "ar": "Arabic", "hy": "Armenian", 
    "as": "Assamese", "az": "Azerbaijani", "eu": "Basque", "be": "Belarusian", "bs": "Bosnian", 
    "bg": "Bulgarian", "my": "Burmese", "ca": "Catalan", "ckb": "Central Kurdish", "zh-cn": "Chinese (Simplified)", 
    "zh-tw": "Chinese (Traditional)", "co": "Corsican", "hr": "Croatian", "cs": "Czech", "da": "Danish", 
    "nl": "Dutch", "en": "English", "et": "Estonian", "fil": "Filipino", "fi": "Finnish", "fr": "French", 
    "gl": "Galician", "ka": "Georgian", "de": "German", "gom": "Goan Konkani", "el": "Greek", "gn": "Guarani", 
    "gu": "Gujarati", "ht": "Haitian Creole", "haw": "Hawaiian", "he": "Hebrew", "hi": "Hindi", "hmn": "Hmong", 
    "hu": "Hungarian", "is": "Icelandic", "id": "Indonesian", "ga": "Irish", "it": "Italian", "ja": "Japanese", 
    "jv": "Javanese", "kn": "Kannada", "kk": "Kazakh", "km": "Khmer", "rw": "Kinyarwanda", "ko": "Korean", 
    "ku": "Kurdish", "ky": "Kyrgyz", "lo": "Lao", "la": "Latin", "lv": "Latvian", "ln": "Lingala", "lt": "Lithuanian", 
    "lb": "Luxembourgish", "mk": "Macedonian", "mai": "Malagasy", "ms": "Malay", "ml": "Malayalam", 
    "mt": "Maltese", "mi": "Māori", "mr": "Marathi", "mn": "Mongolian", "ne": "Nepali", "nso": "Northern Sotho", 
    "no": "Norwegian", "ny": "Nyanja", "or": "Odia", "om": "Oromo", "ps": "Pashto", "fa": "Persian", "pl": "Polish", 
    "pt": "Portuguese", "pa": "Punjabi", "qu": "Quechua", "ro": "Romanian", "ru": "Russian", "sm": "Samoan", 
    "sa": "Sanskrit", "gd": "Scottish Gaelic", "sr": "Serbian", "sn": "Shona", "sd": "Sindhi", "si": "Sinhala", 
    "sk": "Slovak", "sl": "Slovenian", "so": "Somali", "st": "Southern Sotho", "es": "Spanish", "su": "Sundanese", 
    "sw": "Swahili", "sv": "Swedish", "tg": "Tajik", "ta": "Tamil", "tt": "Tatar", "te": "Telugu", "th": "Thai", 
    "ti": "Tigrinya", "ts": "Tsonga", "tr": "Turkish", "tk": "Turkmen", "uk": "Ukrainian", "ur": "Urdu", "ug": "Uyghur", 
    "uz": "Uzbek", "vi": "Vietnamese", "cy": "Welsh", "fy": "Western Frisian", "xh": "Xhosa", "yi": "Yiddish", 
    "yo": "Yoruba", "zu": "Zulu"
}